### ISSUE TITLE
Request: Shuffle current play queue

### ISSUE THREAD

**Issue by williamkray** [dough10/PolySonic#38] opened 2015-07-27 16:39 UTC
There's a systemwide shuffle option, but it would be nice to load a large playlist and have it play randomly.

**Comment by dough10** [comment] 2015-07-27 19:30
I think this is also doable. I will look into https://github.com/coolaj86/knuth-shuffle for doing the shuffle. Trying to figure out expected behavior. Say the user is already playing a song somewhere down the playlist. i think the best way to deal with that would be to stop currently playing audio. (other wise it looks like the shuffle would cause the player to keep playing the same audio but change all displayed info to what ever song is now marked as playing) shuffle the playlist then set the new first song in the list as playing and start that audio. How does that sound?

**Comment by williamkray** [comment] 2015-07-27 20:49
i think ideal behavior would be any of these (in order of my personal preference):
a) current track continues playing, but playlist shuffles around it. this moves the current track to any position in the playlist, and tracks continue playing randomly.
b) current track continues playing, and the entire playlist remains in order in the view, but toggling the shuffle mode sets the play order invisibly set to select a random track next. nothing visually changes in the playlist, making the shuffle mode a playback feature, rather than a playlist feature.
c) currently playing audio remains playing, but playlist is shuffled underneath it. this makes current track #1 in the shuffled playlist, and the rest of the tracks play randomly afterward

i would say that any of these options make the most sense, from a UX standpoint, it's just a matter of which is easiest to implement for you. from a user experience perspective, you don't want the currently playing track to stop playing and start doing something else random unless the user specifically says "i don't want this song to be playing anymore", which in the use cases above would require either skipping to the next track or stopping playback. paused tracks would follow the same rules as currently playing tracks.

these are just how i would expect the behavior to go, of course. Perhaps play with a common music player (iTunes, WinAmp, and Amarok are heavy hitters on each desktop platform) and see what they default to, this would represent what people will generally expect from a shuffle option.

**Comment by dough10** [comment] 2015-07-27 23:49
you are totally right from UX standpoint i don't wanna stop the music. (was being lazy and trying to find a easy way) but doing it right doesn't appear to any more work. i have set up a function that will copy and remove the playing track from the playlist. it will then shuffle the order of the playlist and add the playing track back to the list at the top also moving the playing indicator to the top position as well. just have to set up button linkage and that will be set for 0.2.6

**Closed** 2015-08-09 18:08 UTC
Labels: enhancement
